[package]
name = "coconut"
version = "0.1.0"
edition = "2021"

[[bin]]
doc = false
name = "coconut"

[build-dependencies]
cfgrammar = "0.13.8"
lrlex = "0.13.8"
lrpar = "0.13.8"

[dependencies]
cfgrammar = "0.13.8"
lrlex = "0.13.8"
lrpar = "0.13.8"
